# Generated by Django 3.2.4 on 2022-10-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityId', models.AutoField(primary_key=True, serialize=False)),
                ('ActivityDate', models.DateField()),
                ('Steps', models.IntegerField()),
                ('Distance', models.IntegerField()),
                ('Run', models.IntegerField()),
                ('Calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Heartrate',
            fields=[
                ('HeartId', models.AutoField(primary_key=True, serialize=False)),
                ('HeartDate', models.DateField()),
                ('Time', models.CharField(max_length=500)),
                ('HeartRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('SleepId', models.AutoField(primary_key=True, serialize=False)),
                ('SleepDate', models.DateField()),
                ('DeepSleepTime', models.IntegerField()),
                ('ShallowSleepTime', models.IntegerField()),
                ('WakeTime', models.IntegerField()),
                ('Start', models.DateField()),
                ('End', models.DateField()),
            ],
        ),
    ]
